updated
updated

User prompt:

werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'listing.list_apartments'. Did you mean 'listing_controller.list_apartments' instead? now fix this error  and the amenitities on the listing page also needs to be fixed

Replit-Commit-Author: eking
Replit-Commit-Session-Id: 07f51bc2-4334-4f88-be7c-942ffbb5c120